export const monitorConfig = {
  jiraRequest: {
    delayBetweenRequestsMs: 500,
    maxIssuesPerBatch: 25,
  },
  notifications: {
    unreadReminderIntervalMinutes: 60,
  },
  issueTypesToPersist: [
    "Testing",
    "Testing de Criterios",
    "Testing Pre-Produccion",
    "Testing Criterios Pre-Produccion",
    "Criterios de aceptacion",
    "Test criterios de aceptacion",
    "Documentar Criterios de Aceptacion",
    "Solicitud de Paso a TEST",
    "Solicitud Paso a Pre-Produccion",
    "Solicitud Paso a Produccion",
    "Implementacion Q&A",
    "Criterios - Pruebas Automaticas",
    "Criterios Pre-Produccion",
    "Admon Pre-Produccion",
    "Subtarea",
    "Aprobacion",
    "Correccion por Testing",
    "Reglas de firewall",
  ],
  linkedProjectsToPersist: ["MDI"],
  attributes: [
    { key: "issueKey", label: "Jira", path: "key", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "jiraId", label: "ID Jira", path: "id", type: "string", filterable: false, gridColumn: false, detail: true },
    { key: "selfUrl", label: "URL REST", path: "self", type: "string", filterable: false, gridColumn: false, detail: true },
    { key: "projectKey", label: "Proyecto Jira", path: "fields.project.key", type: "string", filterable: true, gridColumn: true, detail: true },
    { key: "projectName", label: "Nombre Proyecto", path: "fields.project.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "issueType", label: "Tipo de incidencia", path: "fields.issuetype.name", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "status", label: "Estado", path: "fields.status.name", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "statusCategory", label: "Categoria estado", path: "fields.status.statusCategory.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "summary", label: "Resumen", path: "fields.summary", type: "string", filterable: true, gridColumn: true, detail: true },
    { key: "description", label: "Descripcion", path: "fields.description", type: "object", filterable: false, gridColumn: false, detail: true },
    { key: "assignee", label: "Responsable", path: "fields.assignee.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "reporter", label: "Reportador", path: "fields.reporter.displayName", type: "user", filterable: true, gridColumn: false, detail: true },
    { key: "creator", label: "Creador", path: "fields.creator.displayName", type: "user", filterable: true, gridColumn: false, detail: true },
    { key: "developer", label: "Desarrollador", path: "fields.customfield_XXXXX.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "tester", label: "Tester", path: "fields.customfield_YYYYY.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "criteriaResponsible", label: "Responsable Criterios", path: "fields.customfield_ZZZZZ.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "priority", label: "Prioridad", path: "fields.priority.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "labels", label: "Etiquetas", path: "fields.labels", type: "stringList", filterable: true, gridColumn: false, detail: true },
    { key: "createdAt", label: "Creado", path: "fields.created", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "updatedAt", label: "Actualizado", path: "fields.updated", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "resolution", label: "Resolucion", path: "fields.resolution.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "resolutionDate", label: "Fecha resolucion", path: "fields.resolutiondate", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "timeOriginalEstimate", label: "Tiempo planeado", path: "fields.timeoriginalestimate", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "timeSpent", label: "Tiempo registrado", path: "fields.timespent", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "timeRemainingEstimate", label: "Tiempo restante", path: "fields.timeestimate", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "parentIssueKey", label: "Jira padre", path: "fields.parent.key", type: "string", filterable: true, gridColumn: false, detail: true, calculationInput: true },
  ],
  defaultGridColumns: [
    "description",
    "generalStatus",
    "testingIssue",
    "testOwner",
    "developer",
    "plannedTimeHours",
    "spentTimeHours",
    "remainingTimeHours",
    "criteriaTestingIssue",
    "criteriaDocIssue",
    "criteriaOwner",
    "corrections",
    "automationIssue",
    "trackingIssue",
    "testDeployIssue",
    "admonIssue",
    "preProdDeployIssue",
    "preProdDeployOpenSubtaskKeys",
    "firewallIssue",
    "infrastructureIssue",
    "preProdTestingIssue",
    "preProdCriteriaTestingIssue",
    "preProdCriteriaDocIssue",
  ],
};

export const gridColumnDefinitions = [
  { key: "description", label: "Descripcion", type: "text" },
  { key: "generalStatus", label: "Estado general", type: "text" },
  { key: "testingIssue", label: "Jira Testing", type: "issueKey" },
  { key: "testOwner", label: "Responsable Pruebas", type: "text" },
  { key: "developer", label: "Desarrollador", type: "text" },
  { key: "plannedTimeHours", label: "Tiempo planeado", type: "number" },
  { key: "spentTimeHours", label: "Tiempo Registrado", type: "number" },
  { key: "remainingTimeHours", label: "Tiempo restante", type: "number" },
  { key: "criteriaTestingIssue", label: "Testing de Criterios", type: "issueKey" },
  { key: "criteriaTestingOwner", label: "Responsable Testing Criterios", type: "text" },
  { key: "criteriaTestingStatus", label: "Estado Testing Criterios", type: "text" },
  { key: "criteriaDocIssue", label: "Documentacion de criterios", type: "issueKey" },
  { key: "criteriaDocStatus", label: "Estado criterios", type: "text" },
  { key: "criteriaOwner", label: "Responsable Criterios", type: "text" },
  { key: "criteriaPlannedTimeHours", label: "Tiempo planeado criterios", type: "number" },
  { key: "criteriaSpentTimeHours", label: "Tiempo registrado criterios", type: "number" },
  { key: "criteriaRemainingTimeHours", label: "Tiempo restante criterios", type: "number" },
  { key: "corrections", label: "Correcciones", type: "number" },
  { key: "automationIssue", label: "Automatizacion", type: "issueKey" },
  { key: "automationOwner", label: "Responsable Automatizacion", type: "text" },
  { key: "automationStatus", label: "Estado Automatizacion", type: "text" },
  { key: "trackingIssue", label: "Seguimiento", type: "issueKey" },
  { key: "trackingOwner", label: "Responsable seguimiento", type: "text" },
  { key: "trackingStatus", label: "Estado seguimiento", type: "text" },
  { key: "testDeployIssue", label: "Montaje Test", type: "issueKey" },
  { key: "testDeployOwner", label: "Responsable Montaje Test", type: "text" },
  { key: "testDeployStatus", label: "Estado Montaje Test", type: "text" },
  { key: "admonIssue", label: "Admon", type: "issueKey" },
  { key: "admonOwner", label: "Responsable Admon", type: "text" },
  { key: "admonStatus", label: "Estado Admon", type: "text" },
  { key: "preProdDeployIssue", label: "Montaje Pre-Produccion", type: "issueKey" },
  { key: "preProdDeployOwner", label: "Responsable Montaje Pre", type: "text" },
  { key: "preProdDeployStatus", label: "Estado Montaje Pre", type: "text" },
  { key: "preProdDeployTotalSubtasks", label: "Total subtareas Pre", type: "number" },
  { key: "preProdDeployOpenSubtasks", label: "Subtareas abiertas Pre", type: "number" },
  { key: "preProdDeployOpenSubtaskKeys", label: "Jiras subtareas abiertas Pre", type: "issueKey" },
  { key: "preProdDeployUndefinedSubtasks", label: "Subtareas no definidas Pre", type: "number" },
  { key: "preProdDeployUndefinedSubtaskKeys", label: "Jiras subtareas no definidas Pre", type: "issueKey" },
  { key: "prodDeployIssue", label: "Montaje Produccion", type: "issueKey" },
  { key: "prodDeployOwner", label: "Responsable Montaje Produccion", type: "text" },
  { key: "prodDeployStatus", label: "Estado Montaje Produccion", type: "text" },
  { key: "prodDeployTotalSubtasks", label: "Total subtareas Prod", type: "number" },
  { key: "prodDeployOpenSubtasks", label: "Subtareas abiertas Prod", type: "number" },
  { key: "prodDeployOpenSubtaskKeys", label: "Jiras subtareas abiertas Prod", type: "issueKey" },
  { key: "prodDeployUndefinedSubtasks", label: "Subtareas no definidas Prod", type: "number" },
  { key: "prodDeployUndefinedSubtaskKeys", label: "Jiras subtareas no definidas Prod", type: "issueKey" },
  { key: "firewallIssue", label: "Reglas de Firewall", type: "issueKey" },
  { key: "firewallOwner", label: "Responsable Firewall", type: "text" },
  { key: "firewallStatus", label: "Estado Firewall", type: "text" },
  { key: "infrastructureIssue", label: "Intervencion infraestructura", type: "issueKey" },
  { key: "infrastructureOwner", label: "Responsable infraestructura", type: "text" },
  { key: "infrastructureStatus", label: "Estado infraestructura", type: "text" },
  { key: "preProdTestingIssue", label: "Testing Pre-Produccion", type: "issueKey" },
  { key: "preProdTestingOwner", label: "Responsable Pruebas Pre", type: "text" },
  { key: "preProdTestingStatus", label: "Estado Testing Pre", type: "text" },
  { key: "preProdCriteriaTestingIssue", label: "Testing Criterios Pre-Produccion", type: "issueKey" },
  { key: "preProdCriteriaTestingOwner", label: "Responsable Testing Criterios Pre", type: "text" },
  { key: "preProdCriteriaTestingStatus", label: "Estado Testing Criterios Pre", type: "text" },
  { key: "preProdCriteriaDocIssue", label: "Documentacion criterios Pre", type: "issueKey" },
  { key: "preProdCriteriaDocOwner", label: "Responsable criterios Pre", type: "text" },
  { key: "preProdCriteriaDocStatus", label: "Estado criterios Pre", type: "text" },
  { key: "closedCriteriaPercent", label: "% jiras cerrados", type: "percent" },
];

export const operatorsByType = {
  string: ["=", "!=", "contains", "not_contains"],
  user: ["=", "!=", "contains", "not_contains"],
  number: ["=", "!=", ">", ">=", "<", "<="],
  date: ["=", "!=", ">", ">=", "<", "<="],
  boolean: ["=", "!="],
};
