export const monitorConfig = {
  jiraRequest: {
    delayBetweenRequestsMs: 500,
    maxIssuesPerBatch: 25,
  },
  notifications: {
    unreadReminderIntervalMinutes: 60,
  },
  issueTypesToPersist: [
    "Testing",
    "Testing de Criterios",
    "Testing Pre-Producción",
	"Criterios de aceptación"
    /*"Testing Criterios Pre-Producción",    
    "Test criterios de aceptación",
    "Documentar Criterios de Aceptación",
    "Solicitud de Paso a TEST",
    "Solicitud Paso a Pre-Producción",
    "Solicitud Paso a Producción",
    "Implementación Q&A",
    "Criterios – Pruebas Automáticas",
    "Criterios Pre-Producción",
    "Admon Pre-Produccion",
    "Subtarea",
    "Aprobación",*/
  ],
  attributes: [
    { key: "issueKey", label: "Jira", path: "key", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "jiraId", label: "ID Jira", path: "id", type: "string", filterable: false, gridColumn: false, detail: true },
    { key: "selfUrl", label: "URL REST", path: "self", type: "string", filterable: false, gridColumn: false, detail: true },
    { key: "projectKey", label: "Proyecto Jira", path: "fields.project.key", type: "string", filterable: true, gridColumn: true, detail: true },
    { key: "projectName", label: "Nombre Proyecto", path: "fields.project.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "issueType", label: "Tipo de incidencia", path: "fields.issuetype.name", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "status", label: "Estado", path: "fields.status.name", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "statusCategory", label: "Categoría estado", path: "fields.status.statusCategory.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "summary", label: "Resumen", path: "fields.summary", type: "string", filterable: true, gridColumn: true, detail: true },
    { key: "description", label: "Descripción", path: "fields.description", type: "object", filterable: false, gridColumn: false, detail: true },
    { key: "assignee", label: "Responsable", path: "fields.assignee.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "reporter", label: "Reportador", path: "fields.reporter.displayName", type: "user", filterable: true, gridColumn: false, detail: true },
    { key: "creator", label: "Creador", path: "fields.creator.displayName", type: "user", filterable: true, gridColumn: false, detail: true },
    { key: "developer", label: "Desarrollador", path: "fields.customfield_XXXXX.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "tester", label: "Tester", path: "fields.customfield_YYYYY.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "criteriaResponsible", label: "Responsable Criterios", path: "fields.customfield_ZZZZZ.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "priority", label: "Prioridad", path: "fields.priority.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "labels", label: "Etiquetas", path: "fields.labels", type: "stringList", filterable: true, gridColumn: false, detail: true },
    { key: "createdAt", label: "Creado", path: "fields.created", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "updatedAt", label: "Actualizado", path: "fields.updated", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "resolution", label: "Resolución", path: "fields.resolution.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "resolutionDate", label: "Fecha resolución", path: "fields.resolutiondate", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "timeOriginalEstimate", label: "Tiempo planeado", path: "fields.timeoriginalestimate", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "timeSpent", label: "Tiempo registrado", path: "fields.timespent", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "timeRemainingEstimate", label: "Tiempo restante", path: "fields.timeestimate", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
  ],
  defaultGridColumns: [
    "description",
    "generalStatus",
    "testingIssue",
    "testOwner",
    "developer"
 /*   "criteriaDocIssue",
    "criteriaOwner",
    "corrections",
    "automationIssue",
    "testDeployIssue",
    "closedCriteriaPercent",
    "plannedTimeHours",
    "spentTimeHours",
    "remainingTimeHours",*/
  ],
};

export const gridColumnDefinitions = [
  { key: "description", label: "Descripción", type: "text" },
  { key: "generalStatus", label: "Estado general", type: "text" },
  { key: "testingIssue", label: "Jira Testing", type: "issueKey" },
  { key: "testOwner", label: "Responsable Pruebas", type: "text" },
  { key: "developer", label: "Desarrollador", type: "text" },
  { key: "criteriaDocIssue", label: "Documentación de criterios", type: "issueKey" },
  { key: "criteriaOwner", label: "Responsable Criterios", type: "text" },
  { key: "corrections", label: "Correcciones", type: "number" },
  { key: "automationIssue", label: "Automatización", type: "issueKey" },
  { key: "testDeployIssue", label: "Montaje Test", type: "issueKey" },
  { key: "closedCriteriaPercent", label: "% jiras cerrados", type: "percent" },
  { key: "plannedTimeHours", label: "Tiempo planeado", type: "number" },
  { key: "spentTimeHours", label: "Tiempo Registrado", type: "number" },
  { key: "remainingTimeHours", label: "Tiempo restante (h)", type: "number" },
];

export const operatorsByType = {
  string: ["=", "!=", "contains", "not_contains"],
  user: ["=", "!=", "contains", "not_contains"],
  number: ["=", "!=", ">", ">=", "<", "<="],
  date: ["=", "!=", ">", ">=", "<", "<="],
  boolean: ["=", "!="],
};
