export const monitorConfig = {
  jiraRequest: {
    delayBetweenRequestsMs: 100,
    maxIssuesPerBatch: 25,
  },
  notifications: {
    unreadReminderIntervalMinutes: 60,
  },
  autoSyncSchedule: {
    weeklyWindows: [
      { days: [1, 2, 3, 4, 5], start: "09:00", end: "12:00" },
      { days: [1, 2, 3, 4, 5], start: "13:00", end: "17:30" },
      { days: [6], start: "07:30", end: "11:30" },
    ],
    specificDates: [
      { month: 1, day: 1, start: "00:00", end: "23:59" },
      { month: 12, day: 7, start: "00:00", end: "23:59" },
    ],
  },
  issueTypesToPersist: [
    "Testing",
    "Testing de Criterios",
    "Testing Pre-Produccion",
    "Testing Criterios Pre-Produccion",
    "Criterios de aceptacion",
    "Test criterios de aceptacion",
    "Documentar Criterios de Aceptacion",
    "Solicitud de Paso a TEST",
    "Solicitud Paso a Pre-Produccion",
    "Solicitud Paso a Produccion",
    "Implementacion Q&A",
    "Criterios - Pruebas Automaticas",
    "Criterios Pre-Produccion",
    "Admon Pre-Produccion",
    "Subtarea",
    "Aprobacion",
    "Correccion por Testing",
    "Reglas de firewall",
  ],
  linkedProjectsToPersist: ["MDI"],
  attributes: [
    { key: "issueKey", label: "Jira", path: "key", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "jiraId", label: "ID Jira", path: "id", type: "string", filterable: false, gridColumn: false, detail: true },
    { key: "selfUrl", label: "URL REST", path: "self", type: "string", filterable: false, gridColumn: false, detail: true },
    { key: "projectKey", label: "Proyecto Jira", path: "fields.project.key", type: "string", filterable: true, gridColumn: true, detail: true },
    { key: "projectName", label: "Nombre Proyecto", path: "fields.project.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "issueType", label: "Tipo de incidencia", path: "fields.issuetype.name", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "status", label: "Estado", path: "fields.status.name", type: "string", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "statusCategory", label: "Categoria estado", path: "fields.status.statusCategory.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "summary", label: "Resumen", path: "fields.summary", type: "string", filterable: true, gridColumn: true, detail: true },
    { key: "description", label: "Descripcion", path: "fields.description", type: "object", filterable: false, gridColumn: false, detail: true },
    { key: "assignee", label: "Responsable", path: "fields.assignee.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "reporter", label: "Reportador", path: "fields.reporter.displayName", type: "user", filterable: true, gridColumn: false, detail: true },
    { key: "creator", label: "Creador", path: "fields.creator.displayName", type: "user", filterable: true, gridColumn: false, detail: true },
    { key: "developer", label: "Desarrollador", path: "fields.customfield_XXXXX.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "tester", label: "Tester", path: "fields.customfield_YYYYY.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "criteriaResponsible", label: "Responsable Criterios", path: "fields.customfield_ZZZZZ.displayName", type: "user", filterable: true, gridColumn: true, detail: true },
    { key: "priority", label: "Prioridad", path: "fields.priority.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "labels", label: "Etiquetas", path: "fields.labels", type: "stringList", filterable: true, gridColumn: false, detail: true },
    { key: "createdAt", label: "Creado", path: "fields.created", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "updatedAt", label: "Actualizado", path: "fields.updated", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "resolution", label: "Resolucion", path: "fields.resolution.name", type: "string", filterable: true, gridColumn: false, detail: true },
    { key: "resolutionDate", label: "Fecha resolucion", path: "fields.resolutiondate", type: "date", filterable: true, gridColumn: false, detail: true },
    { key: "timeOriginalEstimate", label: "Tiempo planeado", path: "fields.timeoriginalestimate", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "timeSpent", label: "Tiempo registrado", path: "fields.timespent", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "timeRemainingEstimate", label: "Tiempo restante", path: "fields.timeestimate", type: "number", filterable: true, gridColumn: true, detail: true, calculationInput: true },
    { key: "parentIssueKey", label: "Jira padre", path: "fields.parent.key", type: "string", filterable: true, gridColumn: false, detail: true, calculationInput: true },
  ],
  defaultGridColumns: [
    "description",
    "generalStatus",
    "testing",
    "criteriaTesting",
    "criteriaDoc",
    "corrections",
    "automation",
    "tracking",
    "testDeploy",
    "admon",
    "preProdDeploy",
    "firewall",
    "infrastructure",
    "preProdTesting",
    "preProdCriteriaTesting",
    "preProdCriteriaDoc",
  ],
};

export const gridColumnDefinitions = [
  { key: "description", label: "Descripcion", type: "text" },
  { key: "generalStatus", label: "Estado general", type: "text" },
  { key: "testing", label: "Testing", type: "issueSummary" },
  { key: "criteriaTesting", label: "Testing de Criterios", type: "issueSummary" },
  { key: "criteriaDoc", label: "Documentacion de criterios", type: "issueSummary" },
  { key: "corrections", label: "Correcciones", type: "number" },
  { key: "automation", label: "Automatizacion", type: "issueSummary" },
  { key: "tracking", label: "Seguimiento", type: "issueSummary" },
  { key: "testDeploy", label: "Montaje Test", type: "issueSummary" },
  { key: "admon", label: "Admon", type: "issueSummary" },
  { key: "preProdDeploy", label: "Montaje Pre-Produccion", type: "issueSummary" },
  { key: "prodDeploy", label: "Montaje Produccion", type: "issueSummary" },
  { key: "firewall", label: "Reglas de Firewall", type: "issueSummary" },
  { key: "infrastructure", label: "Infraestructura", type: "issueSummary" },
  { key: "preProdTesting", label: "Pruebas Pre-Prod", type: "issueSummary" },
  { key: "preProdCriteriaTesting", label: "Criterios Pre-Prod", type: "issueSummary" },
  { key: "preProdCriteriaDoc", label: "Documentacion criterios Pre", type: "issueSummary" },
  { key: "closedCriteriaPercent", label: "% jiras cerrados", type: "percent" },
];

export const operatorsByType = {
  string: ["=", "!=", "contains", "not_contains"],
  user: ["=", "!=", "contains", "not_contains"],
  number: ["=", "!=", ">", ">=", "<", "<="],
  date: ["=", "!=", ">", ">=", "<", "<="],
  boolean: ["=", "!="],
};
